# Generated by Django 5.0.6 on 2024-09-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="auth_type",
            field=models.CharField(
                choices=[
                    ("GOOGLE", "Google Account"),
                    ("FACEBOOK", "Facebook Account"),
                    ("TELEGRAM", "Telegram Account"),
                    ("WITH EMAIL", "Email Auth"),
                    ("WITH PHONE", "Phone Auth"),
                ],
                default="WITH PHONE",
                max_length=244,
                unique=True,
                verbose_name="auth type",
            ),
        ),
    ]
