# Generated by Django 5.0.6 on 2024-09-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_user_auth_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="auth_type",
            field=models.CharField(
                choices=[
                    ("GOOGLE", "Google Account"),
                    ("FACEBOOK", "Facebook Account"),
                    ("TELEGRAM", "Telegram Account"),
                    ("WITH EMAIL", "Email Auth"),
                    ("WITH PHONE", "Phone Auth"),
                ],
                default="WITH PHONE",
                max_length=244,
                verbose_name="auth type",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="device_id",
            field=models.CharField(
                blank=True, max_length=244, null=True, verbose_name="device id"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="phone number"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
    ]
