# Generated by Django 5.0 on 2024-09-28 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_user_auth_type_alter_user_telegram_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntroQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Introduction question"
                    ),
                ),
                ("more_info", models.TextField(verbose_name="More info")),
            ],
        ),
        migrations.CreateModel(
            name="IntroQuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Answer")),
                (
                    "intro_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.introquestion",
                        verbose_name="Question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserIntroQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_marked", models.BooleanField(default=True)),
                (
                    "answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="account.introquestionanswer",
                        verbose_name="Answer",
                    ),
                ),
                (
                    "intro_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.introquestion",
                        verbose_name="Question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
