# Generated by Django 5.0.6 on 2024-09-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_user_auth_type_alter_user_device_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                null=True,
                verbose_name="gender",
            ),
        ),
    ]
