# Generated by Django 5.0.6 on 2024-09-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="father_name",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="father name"
            ),
        ),
    ]
