# Generated by Django 4.2.14 on 2024-08-06 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_email_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_user_id', models.IntegerField(blank=True, null=True, verbose_name='User id')),
                ('provider', models.CharField(choices=[('google', 'google'), ('facebook', 'facebook'), ('telegram', 'telegram')], verbose_name='Provider')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('extra_data', models.JSONField(default=dict, verbose_name='Extra data')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
