# Generated by Django 4.2 on 2024-09-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_user_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
        migrations.AlterField(
            model_name="user",
            name="auth_type",
            field=models.CharField(
                choices=[
                    ("GOOGLE", "Google Account"),
                    ("FACEBOOK", "Facebook Account"),
                    ("TELEGRAM", "Telegram Account"),
                    ("WITH EMAIL", "Email Auth"),
                    ("WITH PHONE", "Phone Auth"),
                ],
                max_length=244,
                unique=True,
                verbose_name="auth type",
            ),
        ),
    ]
