# Generated by Django 4.2 on 2024-09-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_remove_user_gender_alter_user_auth_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                null=True,
                verbose_name="gender",
            ),
        ),
    ]
