# Generated by Django 4.2.14 on 2024-08-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_socialuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_type',
            field=models.CharField(choices=[('GOOGLE', 'Google Account'), ('FACEBOOK', 'Facebook Account'), ('TELEGRAM', 'Telegram Account'), ('WITH EMAIL', 'Email Account')], default='WITH EMAIL', verbose_name='auth type'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SocialUser',
        ),
    ]
