# Generated by Django 4.1 on 2024-08-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_alter_socialuser_provider_alter_user_auth_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialuser",
            name="provider",
            field=models.CharField(
                choices=[
                    ("google", "google"),
                    ("facebook", "facebook"),
                    ("telegram", "telegram"),
                ],
                default="google",
                max_length=255,
                verbose_name="provider",
            ),
        ),
    ]
