version: '3.8'


services:
  db:
    container_name: bumendb
    image: postgres
    environment:
      POSTGRES_NAME: dbmen
      POSTGRES_USER: menadmin
      POSTGRES_PASSWORD: 321
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    volumes:
      - bumen:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: bumenredis
    image: redis
    restart: always
    
  web:
    container_name: bumenweb
    build: 
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - media:/bumen/data/media
      - static:/bumen/data/static

    command: gunicorn --bind 0.0.0.0:8888 core.wsgi:application
    restart: always
  
  celery:
    container_name: bumencelery
    depends_on:
      - redis
      - db
    build: .
    command: celery -A core worker -l INFO





    
volumes:
  media:
  static:
  bumen: