version: '3.7'

services:
  db:
    container_name: bumen_db
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    restart: always
    env_file:
      - .env

  web:
    container_name: bumen_web
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile

    volumes:
      - .:/app
      - ./static:/home/app/web/static
      - ./media:/home/app/web/media
#      - ./locale:/home/app/web/locale
    env_file: .env
    command: python3 manage.py runserver 0.0.0.0:${PORT}
    ports:
      - ${PORT}:${PORT}

    restart: always


# gunicorn src.core.wsgi:application --bind 0.0.0.0:${PORT} --timeout 120


volumes:
  postgres_data:
