version: '3.8'


services:
  db:
    container_name: bumendb
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}

    restart: always
  web:
    container_name: bumenweb
    build: 
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
      - ./static:/home/app/web/static
      - ./media:/home/app/web/media
#      - ./locale:/home/app/web/locale
    env_file: .env
    command: gunicorn core.wsgi:application --bind 0.0.0.0:${PORT} --timeout 120
    ports:
      - ${PORT}:${PORT}
    command: gunicorn --bind 0.0.0.0:8888 core.wsgi:application
    restart: always
  celery:
    build: .
    command: celery -A core worker -l INFO
    volumes:
      - .:/home/app
    environment:
      - DEBUG=1
      - CELERY_BROKER=${CELERY_BROKER_URL}
      - CELERY_BACKEND=${CELERY_BAKCEND}
    depends_on:
      - web
      - redis
    env_file:
      - .env
  redis:
    image: "redis:alpine"

    
volumes:
  media:
  static:
  bumen:
