# Generated by Django 4.2.14 on 2024-08-02 07:42

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('description_uz', models.TextField(null=True, verbose_name='description')),
                ('description_ru', models.TextField(null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('media_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.media', verbose_name='media')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='NewsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News view',
                'verbose_name_plural': 'News views',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.media', verbose_name='file')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsImage', to='news.news', verbose_name='news')),
            ],
            options={
                'verbose_name': 'News Image',
                'verbose_name_plural': 'News Images',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='news_views', to='news.newsview', verbose_name='views'),
        ),
    ]
