# Generated by Django 4.2 on 2024-09-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="image",
        ),
        migrations.AddField(
            model_name="news",
            name="images",
            field=models.ManyToManyField(related_name="news", to="common.media"),
        ),
    ]
