# Generated by Django 4.2 on 2024-09-30 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("news", "0002_remove_news_image_news_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="images",
        ),
        migrations.CreateModel(
            name="NewsImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_images",
                        to="common.media",
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_images",
                        to="news.news",
                    ),
                ),
            ],
            options={
                "verbose_name": "news image",
                "verbose_name_plural": "news images",
            },
        ),
    ]
