# Generated by Django 4.2 on 2024-10-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_remove_news_images_newsimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="description_uz_cyrl",
            field=models.TextField(null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="news",
            name="title_uz_cyrl",
            field=models.CharField(max_length=255, null=True, verbose_name="title"),
        ),
    ]
