# Generated by Django 4.2.14 on 2024-08-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(blank=True, choices=[('image', 'image'), ('music', 'video'), ('audio', 'audio'), ('file', 'file'), ('video', 'video')], max_length=30, verbose_name='type'),
        ),
    ]
