# Generated by Django 5.0.8 on 2024-10-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("discount_percentage", models.PositiveIntegerField()),
                ("description", models.TextField()),
                ("image_url", models.URLField(max_length=500)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
