# Generated by Django 5.0.8 on 2024-09-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubject",
            name="finished",
            field=models.BooleanField(default=False),
        ),
    ]
