# Generated by Django 5.1.1 on 2024-10-04 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="subject_title",
        ),
        migrations.AddField(
            model_name="subject",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="supject.category",
                verbose_name="Category",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="SubjectTitle",
        ),
    ]
