# Generated by Django 5.0.8 on 2024-10-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supject", "0003_transaction_usercard"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transaction",
            },
        ),
        migrations.AlterModelOptions(
            name="usercard",
            options={"verbose_name": "UserCard", "verbose_name_plural": "UserCard"},
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="amount"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="timestamp"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("KIRIM", "Kirim"), ("CHIQUIM", "Chiqim")],
                max_length=10,
                verbose_name="transaction_type",
            ),
        ),
        migrations.AlterField(
            model_name="usercard",
            name="card_number",
            field=models.CharField(max_length=16, verbose_name="card_number"),
        ),
        migrations.AlterField(
            model_name="usercard",
            name="expiry_date",
            field=models.CharField(max_length=5, verbose_name="expiry_date"),
        ),
    ]
