# Generated by Django 5.0 on 2024-09-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "supject",
            "0003_testanswer_test_quetion_usertestresult_total_result_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubject",
            name="finished",
            field=models.BooleanField(default=False),
        ),
    ]
