# Generated by Django 4.2.14 on 2024-08-02 07:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'About Mistake',
                'verbose_name_plural': 'About Mistakes',
            },
        ),
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'App Info',
                'verbose_name_plural': 'App Info',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=200, verbose_name='Adress')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Contacts',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='ContactUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('msg', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact US',
                'verbose_name_plural': 'Contact US',
            },
        ),
        migrations.CreateModel(
            name='ContactWithUsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Contact With Us Category',
                'verbose_name_plural': 'Contact With Us Category',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policy',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.URLField(verbose_name='Telegram URL')),
                ('likedin', models.URLField(verbose_name='LinkedIN URL')),
                ('facebook', models.URLField(verbose_name='Facebook URL')),
                ('instagram', models.URLField(verbose_name='Instagram URL')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.media', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
            },
        ),
        migrations.CreateModel(
            name='ContactWithUsReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_with_us_reasons', to='company.contactwithuscategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Contact With Us Reason',
                'verbose_name_plural': 'Contact With Us Reason',
            },
        ),
        migrations.CreateModel(
            name='ContactWithUsMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Text')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.media', verbose_name='File')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.contactwithusreason', verbose_name='Reason')),
            ],
            options={
                'verbose_name': 'Contact With Us Mobile',
                'verbose_name_plural': 'Contact With Us Mobile',
            },
        ),
    ]
