# Generated by Django 4.2 on 2024-10-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="answer_uz_cyrl",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_uz_cyrl",
            field=models.TextField(null=True),
        ),
    ]
