# Generated by Django 5.1.1 on 2024-10-04 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_faq_answer_uz_cyrl_faq_question_uz_cyrl"),
    ]

    operations = [
        migrations.RenameField(
            model_name="faq",
            old_name="answer_uz_cyrl",
            new_name="answer_uk",
        ),
        migrations.RenameField(
            model_name="faq",
            old_name="question_uz_cyrl",
            new_name="question_uk",
        ),
    ]
